/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electricvoting;

import java.io.File;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Prantik
 */
public class AdvancedSettings extends javax.swing.JFrame {

    /**
     * Creates new form AdvancedSettings
     */
    public AdvancedSettings() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        password = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        email = new javax.swing.JRadioButton();
        multiple = new javax.swing.JRadioButton();
        editable = new javax.swing.JRadioButton();
        stats = new javax.swing.JRadioButton();
        canAdd = new javax.swing.JRadioButton();
        protection = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        emails = new javax.swing.JTextArea();
        read = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.95F);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(36, 47, 85));
        jPanel1.setForeground(new java.awt.Color(36, 47, 85));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setBackground(new java.awt.Color(36, 47, 85));
        password.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        password.setToolTipText("Password");
        password.setBorder(null);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 240, 43));

        save.setBackground(new java.awt.Color(36, 47, 85));
        save.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 630, 140, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 240, 10));

        email.setBackground(new java.awt.Color(36, 47, 85));
        email.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Enable Email Filtering");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        multiple.setBackground(new java.awt.Color(36, 47, 85));
        multiple.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        multiple.setForeground(new java.awt.Color(255, 255, 255));
        multiple.setText("Select multiple option");
        jPanel1.add(multiple, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        editable.setBackground(new java.awt.Color(36, 47, 85));
        editable.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        editable.setForeground(new java.awt.Color(255, 255, 255));
        editable.setText("Editable");
        jPanel1.add(editable, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        stats.setBackground(new java.awt.Color(36, 47, 85));
        stats.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        stats.setForeground(new java.awt.Color(255, 255, 255));
        stats.setText("Hide Statistics");
        jPanel1.add(stats, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        canAdd.setBackground(new java.awt.Color(36, 47, 85));
        canAdd.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        canAdd.setForeground(new java.awt.Color(255, 255, 255));
        canAdd.setText("Let user add options");
        jPanel1.add(canAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        protection.setBackground(new java.awt.Color(36, 47, 85));
        protection.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        protection.setForeground(new java.awt.Color(255, 255, 255));
        protection.setText("Enable Password Protection");
        jPanel1.add(protection, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, -1, -1));

        emails.setBackground(new java.awt.Color(36, 47, 85));
        emails.setColumns(20);
        emails.setForeground(new java.awt.Color(255, 255, 255));
        emails.setRows(5);
        jScrollPane1.setViewportView(emails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 240, 140));

        read.setBackground(new java.awt.Color(36, 47, 85));
        read.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        read.setForeground(new java.awt.Color(255, 255, 255));
        read.setText("Read from file");
        read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readActionPerformed(evt);
            }
        });
        jPanel1.add(read, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 160, 30));

        cancel.setBackground(new java.awt.Color(36, 47, 85));
        cancel.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        save.setEnabled(false);

        CreatePoll.multiple = multiple.isSelected();
        CreatePoll.editable = editable.isSelected();
        CreatePoll.statsHidden = stats.isSelected();
        CreatePoll.canAdd = canAdd.isSelected();
        CreatePoll.emailf = email.isSelected();
        CreatePoll.emails = emails.getText();
        CreatePoll.pProtection = protection.isSelected();
        CreatePoll.pw = password.getText();

        CreatePoll.window.setVisible(true);
        this.setVisible(false);

        save.setEnabled(true);
    }//GEN-LAST:event_saveActionPerformed

    private void readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readActionPerformed
        read.setEnabled(false);

        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setDialogTitle("Choose a file to read emails from");
        jfc.setMultiSelectionEnabled(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text files only", "txt");
        jfc.addChoosableFileFilter(filter);
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfc.setDialogType(JFileChooser.OPEN_DIALOG);
        jfc.setApproveButtonText("Read");
        jfc.setDragEnabled(true);

        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            try {
                Scanner kb = new Scanner(f);
                while (kb.hasNextLine()) {
                    emails.append(kb.nextLine());
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        read.setEnabled(true);
    }//GEN-LAST:event_readActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        cancel.setEnabled(false);
        CreatePoll.window.setVisible(true);
        this.setVisible(false);
        cancel.setEnabled(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(getLocationOnScreen().x + x - lastX, getLocationOnScreen().y + y - lastY);
        lastX = x;
        lastY = y;
    }//GEN-LAST:event_formMouseDragged

    int lastX, lastY;

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        lastX = evt.getXOnScreen();
        lastY = evt.getYOnScreen();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvancedSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvancedSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvancedSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvancedSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvancedSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton canAdd;
    private javax.swing.JButton cancel;
    private javax.swing.JRadioButton editable;
    private javax.swing.JRadioButton email;
    private javax.swing.JTextArea emails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton multiple;
    private javax.swing.JTextField password;
    private javax.swing.JRadioButton protection;
    private javax.swing.JButton read;
    private javax.swing.JButton save;
    private javax.swing.JRadioButton stats;
    // End of variables declaration//GEN-END:variables
}
