/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electricvoting;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;

/**
 *
 * @author Prantik
 */
public class Dashboard extends javax.swing.JFrame {

    static String email;
    static boolean verified = false;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);

        loadPolls(SQL.MY_POLLS + "'" + email + "'", myPolls, 140);
        loadPolls(SQL.MY_VOTES + getPolls(), votes, 40);
        loadProfile();
        welcome.setText("Welcome, " + fname.getText() + " " + lname.getText());
    }

    private String getPolls() {
        StringBuilder polls = SQL.getMyVotedPolls();

        if (polls.length() == 0) {
            return "0";
        }

        return polls.toString();
    }

    private void loadPolls(String pollQuery, JPanel tab, int startY) {
        ArrayList<Poll> polls = SQL.getPolls(pollQuery);

        JLabel columnHeaders = new JLabel("ID              Date Created              Title");
        columnHeaders.setFont(new Font(welcome.getFont().getName(), Font.BOLD, welcome.getFont().getSize()));
        columnHeaders.setForeground(Color.WHITE);
        columnHeaders.setBackground(new Color(0, 188, 212));
        columnHeaders.setBounds(100, startY, 700, 50);

        JSeparator headerSeparator = new JSeparator();
        headerSeparator.setForeground(Color.white);
        headerSeparator.setBounds(75, startY + 50, 750, 5);
        tab.add(columnHeaders);
        tab.add(headerSeparator);

        for (int i = 0, y = startY + 60; i < polls.size(); i++, y += 45) {
            Poll p = polls.get(i);

            JLabel b = new JLabel(getRow(p));
            b.setFont(welcome.getFont());
            b.setBackground(new Color(0, 188, 212));
            b.setForeground(Color.WHITE);
            b.setBounds(100, y, 700, 50);
            tab.add(b);
            JFrame jf = this;

            b.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    if (p.isProtection() && !p.getCreator().equals(email)) {
                        new Password(p, jf).setVisible(true);
                    } else {
                        new ViewPoll(p).setVisible(true);
                        jf.setVisible(false);
                    }
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                }

                @Override
                public void mouseExited(MouseEvent e) {
                }
            });
        }
    }

    private void loadProfile() {
        try {
            String[] info = SQL.getProfile();

            fname.setText(info[0]);
            lname.setText(info[1]);
            email2.setText(info[2]);
            password.setText(info[3]);
            cpassword.setText(info[3]);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tabs = new javax.swing.JTabbedPane();
        myPolls = new javax.swing.JPanel();
        create = new javax.swing.JButton();
        votes = new javax.swing.JPanel();
        search = new javax.swing.JPanel();
        pid = new javax.swing.JTextField();
        search2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        profile = new javax.swing.JPanel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        cpassword = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Electronic Voting System - Dashboard");
        setBackground(new java.awt.Color(0, 188, 212));
        setForeground(new java.awt.Color(0, 188, 212));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        setOpacity(0.95F);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(36, 47, 85));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        Tabs.setBackground(new java.awt.Color(36, 47, 85));
        Tabs.setForeground(new java.awt.Color(255, 255, 255));
        Tabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        Tabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        Tabs.setAutoscrolls(true);
        Tabs.setFont(new java.awt.Font("Roboto Thin", 0, 36)); // NOI18N
        Tabs.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TabsMouseDragged(evt);
            }
        });
        Tabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabsMousePressed(evt);
            }
        });

        myPolls.setBackground(new java.awt.Color(0, 188, 212));
        myPolls.setForeground(new java.awt.Color(255, 255, 255));
        myPolls.setAutoscrolls(true);
        myPolls.setFont(new java.awt.Font("Roboto Thin", 0, 36)); // NOI18N

        create.setBackground(new java.awt.Color(36, 47, 85));
        create.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myPollsLayout = new javax.swing.GroupLayout(myPolls);
        myPolls.setLayout(myPollsLayout);
        myPollsLayout.setHorizontalGroup(
            myPollsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPollsLayout.createSequentialGroup()
                .addContainerGap(684, Short.MAX_VALUE)
                .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        myPollsLayout.setVerticalGroup(
            myPollsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPollsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );

        Tabs.addTab("My Polls", myPolls);

        votes.setBackground(new java.awt.Color(0, 188, 212));
        votes.setForeground(new java.awt.Color(255, 255, 255));
        votes.setFont(new java.awt.Font("Roboto Thin", 0, 36)); // NOI18N

        javax.swing.GroupLayout votesLayout = new javax.swing.GroupLayout(votes);
        votes.setLayout(votesLayout);
        votesLayout.setHorizontalGroup(
            votesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
        );
        votesLayout.setVerticalGroup(
            votesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        Tabs.addTab("Votes", votes);

        search.setBackground(new java.awt.Color(0, 188, 212));
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Roboto Thin", 0, 36)); // NOI18N

        pid.setBackground(new java.awt.Color(0, 188, 212));
        pid.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        pid.setForeground(new java.awt.Color(255, 255, 255));
        pid.setText("Poll ID");
        pid.setToolTipText("Poll ID");
        pid.setBorder(null);

        search2.setBackground(new java.awt.Color(36, 47, 85));
        search2.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        search2.setForeground(new java.awt.Color(255, 255, 255));
        search2.setText("Search");
        search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search2ActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(search2))
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(search2))
        );

        Tabs.addTab("Search", search);

        profile.setBackground(new java.awt.Color(0, 188, 212));
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setFont(new java.awt.Font("Roboto Thin", 0, 36)); // NOI18N
        profile.setMaximumSize(new java.awt.Dimension(922, 596));
        profile.setMinimumSize(new java.awt.Dimension(922, 596));
        profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fname.setBackground(new java.awt.Color(0, 188, 212));
        fname.setColumns(50);
        fname.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setToolTipText("First Name");
        fname.setBorder(null);
        profile.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 96, 129, 43));

        lname.setBackground(new java.awt.Color(0, 188, 212));
        lname.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setToolTipText("Last Name");
        lname.setBorder(null);
        profile.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 96, 129, 43));

        password.setBackground(new java.awt.Color(0, 188, 212));
        password.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setToolTipText("New Password");
        password.setBorder(null);
        profile.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 264, 43));

        cpassword.setBackground(new java.awt.Color(0, 188, 212));
        cpassword.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        cpassword.setForeground(new java.awt.Color(255, 255, 255));
        cpassword.setToolTipText("Confirm New Password");
        cpassword.setBorder(null);
        profile.add(cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 265, 43));

        update.setBackground(new java.awt.Color(36, 47, 85));
        update.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        profile.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 264, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Thin", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email");
        profile.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 554, 43));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto Thin", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        profile.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 95, 554, 43));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto Thin", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password");
        profile.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 554, 43));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Roboto Thin", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password");
        profile.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 554, 43));

        email2.setBackground(new java.awt.Color(0, 188, 212));
        email2.setColumns(50);
        email2.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        email2.setForeground(new java.awt.Color(255, 255, 255));
        email2.setToolTipText("First Name");
        email2.setBorder(null);
        profile.add(email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 264, 43));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        profile.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 129, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        profile.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 129, 10));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        profile.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 194, 264, 10));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        profile.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 244, 264, 10));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        profile.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 293, 264, 10));

        Tabs.addTab("Profile", profile);

        jPanel2.setBackground(new java.awt.Color(36, 47, 85));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electricvoting/res/Minimize.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizeMousePressed(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electricvoting/res/Exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        welcome.setBackground(new java.awt.Color(36, 47, 85));
        welcome.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(exit))
                        .addComponent(minimize))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit)
                    .addComponent(minimize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        update.setEnabled(false);

        if (fname.getText().length() == 0 || lname.getText().length() == 0 || email2.getText().length() == 0 || password.getText().length() == 0 || cpassword.getText().length() == 0) {
            JOptionPane.showMessageDialog(new JFrame(), "Mandatory fields cannot be left empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (duplicateEmail()) {
            JOptionPane.showMessageDialog(new JFrame(), "An acount associated with your email already exists.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (password.getText().length() < 8 || password.getText().length() > 32) {
            JOptionPane.showMessageDialog(new JFrame(), "Password should be between 8 to 32 characters.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!password.getText().equals(cpassword.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Password do not match confirmed password.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            SQL.updateProfile(fname.getText(), lname.getText(), email2.getText(), password.getText());
        }

        update.setEnabled(true);
    }//GEN-LAST:event_updateActionPerformed

    private void search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search2ActionPerformed
        search2.setEnabled(false);

        if (pid.getText().length() == 0) {
            JOptionPane.showMessageDialog(new JFrame(), "Poll id field cannot be left empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (pid.getText().length() > 11) {
            JOptionPane.showMessageDialog(new JFrame(), "Invalid poll id.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!pid.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(new JFrame(), "Poll id field can only contain numeric values", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            ArrayList<Poll> polls = SQL.getPolls(SQL.SEARCH_POLLS + pid.getText());
            if (polls.size() == 0) {
                JOptionPane.showMessageDialog(new JFrame(), "No polls found.", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                Poll p = polls.get(0);

                if (p.isProtection() && !p.getCreator().equals(email)) {
                    new Password(p, this).setVisible(true);
                } else {
                    new ViewPoll(p).setVisible(true);
                    this.setVisible(false);
                }
            }
        }

        search2.setEnabled(true);
    }//GEN-LAST:event_search2ActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        new CreatePoll().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_createActionPerformed

    private void minimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMousePressed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMousePressed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        lastX = evt.getXOnScreen();
        lastY = evt.getYOnScreen();
    }//GEN-LAST:event_formMousePressed

    int lastX, lastY;

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(getLocationOnScreen().x + x - lastX, getLocationOnScreen().y + y - lastY);
        lastX = x;
        lastY = y;
    }//GEN-LAST:event_formMouseDragged

    private void TabsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabsMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(getLocationOnScreen().x + x - lastX, getLocationOnScreen().y + y - lastY);
        lastX = x;
        lastY = y;
    }//GEN-LAST:event_TabsMouseDragged

    private void TabsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabsMousePressed
        lastX = evt.getXOnScreen();
        lastY = evt.getYOnScreen();
    }//GEN-LAST:event_TabsMousePressed

    private boolean duplicateEmail() {
        if (email.equals(email2.getText())) {
            return false;
        }

        return SQL.getDuplicate(email2.getText());
    }

    private String getRow(Poll p) {
        StringBuilder sb = new StringBuilder();

        sb.append(p.getId());
        int spaces = 19 - sb.length();
        for (int i = 0; i < spaces; i++) {
            sb.append(" ");
        }
        sb.append(p.getCreated().substring(0, 10)).append("                     ");
        sb.append(p.getTitle());

        return sb.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JTextField cpassword;
    private javax.swing.JButton create;
    private javax.swing.JTextField email2;
    private javax.swing.JLabel exit;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel myPolls;
    private javax.swing.JTextField password;
    private javax.swing.JTextField pid;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel search;
    private javax.swing.JButton search2;
    private javax.swing.JButton update;
    private javax.swing.JPanel votes;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
