/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electricvoting;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Prantik
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        signup = new javax.swing.JButton();
        password = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        cpassword = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Electronic Voting System - Signup");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(600, 800));
        setMinimumSize(new java.awt.Dimension(600, 800));
        setUndecorated(true);
        setOpacity(0.95F);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(36, 47, 85));
        jPanel1.setForeground(new java.awt.Color(36, 47, 85));
        jPanel1.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signup.setBackground(new java.awt.Color(36, 47, 85));
        signup.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("Signup");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        jPanel1.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 264, -1));

        password.setBackground(new java.awt.Color(36, 47, 85));
        password.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        password.setToolTipText("Password");
        password.setBorder(null);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 264, 43));

        fname.setBackground(new java.awt.Color(36, 47, 85));
        fname.setColumns(50);
        fname.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setText("First Name");
        fname.setToolTipText("First Name");
        fname.setBorder(null);
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 251, 129, 43));

        email.setBackground(new java.awt.Color(36, 47, 85));
        email.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email");
        email.setToolTipText("Email");
        email.setBorder(null);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 306, 264, 43));

        cpassword.setBackground(new java.awt.Color(36, 47, 85));
        cpassword.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        cpassword.setForeground(new java.awt.Color(255, 255, 255));
        cpassword.setText("Confirm Password");
        cpassword.setToolTipText("Confirm Password");
        cpassword.setBorder(null);
        jPanel1.add(cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 264, 43));

        lname.setBackground(new java.awt.Color(36, 47, 85));
        lname.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setText("Last Name");
        lname.setToolTipText("Last Name");
        lname.setBorder(null);
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 251, 129, 43));

        cancel.setBackground(new java.awt.Color(36, 47, 85));
        cancel.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 264, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 264, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 406, 264, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 300, 129, 10));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 264, 10));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 300, 129, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        signup.setEnabled(false);

        if (fname.getText().length() == 0 || lname.getText().length() == 0 || email.getText().length() == 0 || password.getText().length() == 0 || cpassword.getText().length() == 0) {
            JOptionPane.showMessageDialog(new JFrame(), "Mandatory fields cannot be left empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (duplicateEmail()) {
            JOptionPane.showMessageDialog(new JFrame(), "An acount associated with your email already exists.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (password.getText().length() < 8 || password.getText().length() > 32) {
            JOptionPane.showMessageDialog(new JFrame(), "Password should be between 8 to 32 characters.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!password.getText().equals(cpassword.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Password do not match confirmed password.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            insertUser();
            JOptionPane.showMessageDialog(new JFrame(), "Signup successful.", "Success", JOptionPane.INFORMATION_MESSAGE);
            new Main().setVisible(true);
            this.setVisible(false);
        }

        signup.setEnabled(true);
    }//GEN-LAST:event_signupActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        cancel.setEnabled(false);
        new Main().setVisible(true);
        this.setVisible(false);
        cancel.setEnabled(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        lastX = evt.getXOnScreen();
        lastY = evt.getYOnScreen();
    }//GEN-LAST:event_formMousePressed

    int lastX, lastY;

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(getLocationOnScreen().x + x - lastX, getLocationOnScreen().y + y - lastY);
        lastX = x;
        lastY = y;
    }//GEN-LAST:event_formMouseDragged

    private void insertUser() {
        String vcode = new RandomString(10).nextString();
        SQL.insertUser(fname.getText(), lname.getText(), email.getText(), password.getText(), vcode);
    }

    private boolean duplicateEmail() {
        return SQL.getDuplicate(email.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cpassword;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField password;
    private javax.swing.JButton signup;
    // End of variables declaration//GEN-END:variables
}
